--!strict
--[[
    dump_enums.lua

    Run this in the Roblox Studio command bar (or as a Script). It walks
    every Enum exposed by the running Roblox engine and emits C++ source
    using the RBX_ENUM_BEGIN / RBX_ENUM_VALUE / RBX_ENUM_END macros from
    src/RBX.hpp.

    Paste the output between the existing `namespace Enum { ... }` block in
    RBX.hpp (after the RBX_ENUM_BEGIN macro definitions and before the
    `#undef`s). Items whose names aren't valid C++ identifiers are skipped
    and reported in a trailing comment.

    Usage:
      1. Paste the contents of this file into Studio's command bar.
      2. Press Enter. Output appears in the Output window.
      3. Copy the dumped C++ block into RBX.hpp.
]]

-- C++ keywords + a couple of common type names we want to avoid clashing with.
local RESERVED = {
    ["alignas"]=true, ["alignof"]=true, ["and"]=true, ["and_eq"]=true,
    ["asm"]=true, ["auto"]=true, ["bitand"]=true, ["bitor"]=true,
    ["bool"]=true, ["break"]=true, ["case"]=true, ["catch"]=true,
    ["char"]=true, ["class"]=true, ["compl"]=true, ["concept"]=true,
    ["const"]=true, ["consteval"]=true, ["constexpr"]=true, ["constinit"]=true,
    ["continue"]=true, ["decltype"]=true, ["default"]=true, ["delete"]=true,
    ["do"]=true, ["double"]=true, ["dynamic_cast"]=true, ["else"]=true,
    ["enum"]=true, ["explicit"]=true, ["export"]=true, ["extern"]=true,
    ["false"]=true, ["float"]=true, ["for"]=true, ["friend"]=true,
    ["goto"]=true, ["if"]=true, ["inline"]=true, ["int"]=true,
    ["long"]=true, ["mutable"]=true, ["namespace"]=true, ["new"]=true,
    ["noexcept"]=true, ["not"]=true, ["not_eq"]=true, ["nullptr"]=true,
    ["operator"]=true, ["or"]=true, ["or_eq"]=true, ["private"]=true,
    ["protected"]=true, ["public"]=true, ["register"]=true, ["reinterpret_cast"]=true,
    ["requires"]=true, ["return"]=true, ["short"]=true, ["signed"]=true,
    ["sizeof"]=true, ["static"]=true, ["static_assert"]=true, ["static_cast"]=true,
    ["struct"]=true, ["switch"]=true, ["template"]=true, ["this"]=true,
    ["thread_local"]=true, ["throw"]=true, ["true"]=true, ["try"]=true,
    ["typedef"]=true, ["typeid"]=true, ["typename"]=true, ["union"]=true,
    ["unsigned"]=true, ["using"]=true, ["virtual"]=true, ["void"]=true,
    ["volatile"]=true, ["wchar_t"]=true, ["while"]=true, ["xor"]=true,
    ["xor_eq"]=true,
    -- A few collisions with names already used in src/RBX.hpp:
    ["TypeName"]=true, ["GetEnumItems"]=true, ["FromName"]=true, ["FromValue"]=true,
}

local function isValidIdent(name: string): boolean
    return name:match("^[A-Za-z_][A-Za-z0-9_]*$") ~= nil
        and not RESERVED[name]
end

local function enumTypeName(enum): string
    local s = tostring(enum)               -- e.g. "Enum.EasingStyle"
    return (s:match("Enum%.(.+)") or s)
end

local lines = {}
local skipped = {}                          -- {enumName, itemName, reason}

local enums = Enum:GetEnums()
table.sort(enums, function(a, b)
    return enumTypeName(a) < enumTypeName(b)
end)

table.insert(lines, "// =====================================================================")
table.insert(lines, "// Auto-generated by tools/dump_enums.lua against Roblox engine.")
table.insert(lines, "// Paste between the RBX_ENUM_BEGIN macro defs and the #undefs in")
table.insert(lines, "// the `namespace Enum { ... }` block of src/RBX.hpp.")
table.insert(lines, "// =====================================================================")
table.insert(lines, "")

for _, enum in ipairs(enums) do
    local typeName = enumTypeName(enum)
    if not isValidIdent(typeName) then
        table.insert(skipped, { typeName, "<all>", "invalid type identifier" })
    else
        local items = enum:GetEnumItems()
        local kept = {}                     -- valid item names

        table.insert(lines, ("RBX_ENUM_BEGIN(%s)"):format(typeName))
        for _, item in ipairs(items) do
            if isValidIdent(item.Name) then
                table.insert(lines, ("\tRBX_ENUM_VALUE(%s, %s, %d)")
                    :format(typeName, item.Name, item.Value))
                table.insert(kept, item.Name)
            else
                table.insert(skipped, { typeName, item.Name, "invalid C++ identifier" })
            end
        end

        if #kept == 0 then
            -- Macro requires at least one entry; emit a sentinel so the file
            -- still compiles. Drop the empty type entirely instead.
            -- Roll back the BEGIN we just wrote.
            table.remove(lines)
            table.insert(skipped, { typeName, "<all>", "no valid items" })
        else
            table.insert(lines, ("RBX_ENUM_END(%s, %s)")
                :format(typeName, table.concat(kept, ", ")))
            table.insert(lines, "")
        end
    end
end

if #skipped > 0 then
    table.insert(lines, "// ----- Skipped items (couldn't represent in C++) -------------------")
    for _, entry in ipairs(skipped) do
        table.insert(lines, ("// %s::%s  -- %s"):format(entry[1], entry[2], entry[3]))
    end
end

local output = table.concat(lines, "\n")

-- Studio's Output window truncates long prints, so emit the dump in chunks
-- of up to MAX_CHUNK characters. Splits always happen at a newline boundary
-- so the pasted-together result stays valid C++.
local MAX_CHUNK = 100000

local function splitOnLines(text: string, maxLen: number): {string}
    local chunks = {}
    local start = 1
    local len = #text
    while start <= len do
        local stop = math.min(start + maxLen - 1, len)
        if stop < len then
            -- back up to the previous newline so we don't cut a line in half
            local nl = text:sub(start, stop):find("\n[^\n]*$")
            if nl then
                stop = start + nl - 1
            end
        end
        table.insert(chunks, text:sub(start, stop))
        start = stop + 1
    end
    return chunks
end

local chunks = splitOnLines(output, MAX_CHUNK)
for i, chunk in ipairs(chunks) do
    print(("---- enum dump part %d / %d (%d chars) ----"):format(i, #chunks, #chunk))
    print(chunk)
end

-- If `writefile` is available (some Studio plugins / executors expose it),
-- also drop the result on disk so it's easy to grab.
if (writefile :: any) ~= nil then
    pcall(function()
        (writefile :: any)("RBX_Enums_dump.cpp", output)
    end)
end

return output
